"""Các hằng số và ánh xạ dữ liệu Genshin Impact."""

from typing import Dict, Any

# Bảng mã nhân vật Genshin (ID -> (Tên tiếng Việt, Nguyên tố, Rarity, Icon Name))
GENSHIN_CHARACTERS: Dict[int, Dict[str, Any]] = {
    10000038: {"name": "Albedo", "element": "Geo", "rarity": 5, "icon_name": "UI_AvatarIcon_Albedo"},
    10000078: {"name": "Alhaitham", "element": "Dendro", "rarity": 5, "icon_name": "UI_AvatarIcon_Alhatham"},
    10000057: {"name": "Arataki Itto", "element": "Geo", "rarity": 5, "icon_name": "UI_AvatarIcon_Itto"},
    10000096: {"name": "Arlecchino", "element": "Pyro", "rarity": 5, "icon_name": "UI_AvatarIcon_Arlecchino"},
    10000082: {"name": "Baizhu", "element": "Dendro", "rarity": 5, "icon_name": "UI_AvatarIcon_Baizhuer"},
    10000104: {"name": "Chasca", "element": "Anemo", "rarity": 5, "icon_name": "UI_AvatarIcon_Chasca"},
    10000094: {"name": "Chiori", "element": "Geo", "rarity": 5, "icon_name": "UI_AvatarIcon_Chiori"},
    10000107: {"name": "Citlali", "element": "Cryo", "rarity": 5, "icon_name": "UI_AvatarIcon_Citlali"},
    10000098: {"name": "Clorinde", "element": "Electro", "rarity": 5, "icon_name": "UI_AvatarIcon_Clorinde"},
    10000904: {"name": "Columbina", "element": "Pyro", "rarity": 5, "icon_name": "UI_AvatarIcon_Columbina"},
    10000125: {"name": "Columbina", "element": "Cryo", "rarity": 5, "icon_name": "UI_AvatarIcon_Columbina"},
    10000071: {"name": "Cyno", "element": "Electro", "rarity": 5, "icon_name": "UI_AvatarIcon_Cyno"},
    10000079: {"name": "Dehya", "element": "Pyro", "rarity": 5, "icon_name": "UI_AvatarIcon_Dehya"},
    10000016: {"name": "Diluc", "element": "Pyro", "rarity": 5, "icon_name": "UI_AvatarIcon_Diluc"},
    10000123: {"name": "Durin", "element": "Pyro", "rarity": 5, "icon_name": "UI_AvatarIcon_Durin"},
    10000099: {"name": "Emilie", "element": "Dendro", "rarity": 5, "icon_name": "UI_AvatarIcon_Emilie"},
    10000112: {"name": "Escoffier", "element": "Cryo", "rarity": 5, "icon_name": "UI_AvatarIcon_Escoffier"},
    10000051: {"name": "Eula", "element": "Cryo", "rarity": 5, "icon_name": "UI_AvatarIcon_Eula"},
    10000120: {"name": "Flins", "element": "Electro", "rarity": 5, "icon_name": "UI_AvatarIcon_Flins"},
    10000089: {"name": "Furina", "element": "Hydro", "rarity": 5, "icon_name": "UI_AvatarIcon_Furina"},
    10000037: {"name": "Ganyu", "element": "Cryo", "rarity": 5, "icon_name": "UI_AvatarIcon_Ganyu"},
    10000046: {"name": "Hu Tao", "element": "Pyro", "rarity": 5, "icon_name": "UI_AvatarIcon_Hutao"},
    10000902: {"name": "Hu Tao (Dùng thử)", "element": "Pyro", "rarity": 5, "icon_name": "UI_AvatarIcon_Hutao"},
    10000116: {"name": "Ineffa", "element": "Electro", "rarity": 5, "icon_name": "UI_AvatarIcon_Ineffa"},
    10000903: {"name": "Ineffa", "element": "Electro", "rarity": 5, "icon_name": "UI_AvatarIcon_Ineffa"},
    10000003: {"name": "Jean", "element": "Anemo", "rarity": 5, "icon_name": "UI_AvatarIcon_Qin"},
    10000047: {"name": "Kaedehara Kazuha", "element": "Anemo", "rarity": 5, "icon_name": "UI_AvatarIcon_Kazuha"},
    10000002: {"name": "Kamisato Ayaka", "element": "Cryo", "rarity": 5, "icon_name": "UI_AvatarIcon_Ayaka"},
    10000066: {"name": "Kamisato Ayato", "element": "Hydro", "rarity": 5, "icon_name": "UI_AvatarIcon_Ayato"},
    10000042: {"name": "Keqing", "element": "Electro", "rarity": 5, "icon_name": "UI_AvatarIcon_Keqing"},
    10000101: {"name": "Kinich", "element": "Dendro", "rarity": 5, "icon_name": "UI_AvatarIcon_Kinich"},
    10000029: {"name": "Klee", "element": "Pyro", "rarity": 5, "icon_name": "UI_AvatarIcon_Klee"},
    10000075: {"name": "Kẻ Lang Thang", "element": "Anemo", "rarity": 5, "icon_name": "UI_AvatarIcon_Wanderer"},
    10000119: {"name": "Lauma", "element": "Dendro", "rarity": 5, "icon_name": "UI_AvatarIcon_Lauma"},
    10000084: {"name": "Lyney", "element": "Pyro", "rarity": 5, "icon_name": "UI_AvatarIcon_Liney"},
    10000106: {"name": "Mavuika", "element": "Pyro", "rarity": 5, "icon_name": "UI_AvatarIcon_Mavuika"},
    10000901: {"name": "Mavuika (Thử Nghiệm)", "element": "Pyro", "rarity": 5, "icon_name": "UI_AvatarIcon_Mavuika"},
    10000041: {"name": "Mona", "element": "Hydro", "rarity": 5, "icon_name": "UI_AvatarIcon_Mona"},
    10000102: {"name": "Mualani", "element": "Hydro", "rarity": 5, "icon_name": "UI_AvatarIcon_Mualani"},
    10000073: {"name": "Nahida", "element": "Dendro", "rarity": 5, "icon_name": "UI_AvatarIcon_Nahida"},
    10000091: {"name": "Navia", "element": "Geo", "rarity": 5, "icon_name": "UI_AvatarIcon_Navia"},
    10000122: {"name": "Nefer", "element": "Dendro", "rarity": 5, "icon_name": "UI_AvatarIcon_Nefer"},
    10000087: {"name": "Neuvillette", "element": "Hydro", "rarity": 5, "icon_name": "UI_AvatarIcon_Neuvillette"},
    10000005: {"name": "Nhà Lữ Hành", "element": "Anemo", "rarity": 5, "icon_name": "UI_AvatarIcon_PlayerBoy"},
    10000007: {"name": "Nhà Lữ Hành", "element": "Anemo", "rarity": 5, "icon_name": "UI_AvatarIcon_PlayerGirl"},
    10000070: {"name": "Nilou", "element": "Hydro", "rarity": 5, "icon_name": "UI_AvatarIcon_Nilou"},
    10000035: {"name": "Qiqi", "element": "Cryo", "rarity": 5, "icon_name": "UI_AvatarIcon_Qiqi"},
    10000052: {"name": "Raiden Shogun", "element": "Electro", "rarity": 5, "icon_name": "UI_AvatarIcon_Shougun"},
    10000133: {"name": "Sandrone", "element": "Cryo", "rarity": 5, "icon_name": "UI_AvatarIcon_Sandrone"},
    10000054: {"name": "Sangonomiya Kokomi", "element": "Hydro", "rarity": 5, "icon_name": "UI_AvatarIcon_Kokomi"},
    10000063: {"name": "Shenhe", "element": "Cryo", "rarity": 5, "icon_name": "UI_AvatarIcon_Shenhe"},
    10000095: {"name": "Sigewinne", "element": "Hydro", "rarity": 5, "icon_name": "UI_AvatarIcon_Sigewinne"},
    10000114: {"name": "Skirk", "element": "Cryo", "rarity": 5, "icon_name": "UI_AvatarIcon_SkirkNew"},
    10000033: {"name": "Tartaglia", "element": "Hydro", "rarity": 5, "icon_name": "UI_AvatarIcon_Tartaglia"},
    10000069: {"name": "Tighnari", "element": "Dendro", "rarity": 5, "icon_name": "UI_AvatarIcon_Tighnari"},
    10000111: {"name": "Varesa", "element": "Electro", "rarity": 5, "icon_name": "UI_AvatarIcon_Varesa"},
    10000022: {"name": "Venti", "element": "Anemo", "rarity": 5, "icon_name": "UI_AvatarIcon_Venti"},
    10000086: {"name": "Wriothesley", "element": "Cryo", "rarity": 5, "icon_name": "UI_AvatarIcon_Wriothesley"},
    10000093: {"name": "Xianyun", "element": "Anemo", "rarity": 5, "icon_name": "UI_AvatarIcon_Liuyun"},
    10000026: {"name": "Xiao", "element": "Anemo", "rarity": 5, "icon_name": "UI_AvatarIcon_Xiao"},
    10000103: {"name": "Xilonen", "element": "Geo", "rarity": 5, "icon_name": "UI_AvatarIcon_Xilonen"},
    10000058: {"name": "Yae Miko", "element": "Electro", "rarity": 5, "icon_name": "UI_AvatarIcon_Yae"},
    10000060: {"name": "Yelan", "element": "Hydro", "rarity": 5, "icon_name": "UI_AvatarIcon_Yelan"},
    10000049: {"name": "Yoimiya", "element": "Pyro", "rarity": 5, "icon_name": "UI_AvatarIcon_Yoimiya"},
    10000109: {"name": "Yumemizuki Mizuki", "element": "Anemo", "rarity": 5, "icon_name": "UI_AvatarIcon_Mizuki"},
    10000030: {"name": "Zhongli", "element": "Geo", "rarity": 5, "icon_name": "UI_AvatarIcon_Zhongli"},
    10000121: {"name": "Aino", "element": "Hydro", "rarity": 4, "icon_name": "UI_AvatarIcon_Aino"},
    10000062: {"name": "Aloy", "element": "Cryo", "rarity": 4, "icon_name": "UI_AvatarIcon_Aloy"},
    10000021: {"name": "Amber", "element": "Pyro", "rarity": 4, "icon_name": "UI_AvatarIcon_Ambor"},
    10000014: {"name": "Barbara", "element": "Hydro", "rarity": 4, "icon_name": "UI_AvatarIcon_Barbara"},
    10000024: {"name": "Beidou", "element": "Electro", "rarity": 4, "icon_name": "UI_AvatarIcon_Beidou"},
    10000032: {"name": "Bennett", "element": "Pyro", "rarity": 4, "icon_name": "UI_AvatarIcon_Bennett"},
    10000072: {"name": "Candace", "element": "Hydro", "rarity": 4, "icon_name": "UI_AvatarIcon_Candace"},
    10000088: {"name": "Charlotte", "element": "Cryo", "rarity": 4, "icon_name": "UI_AvatarIcon_Charlotte"},
    10000090: {"name": "Chevreuse", "element": "Pyro", "rarity": 4, "icon_name": "UI_AvatarIcon_Chevreuse"},
    10000036: {"name": "Chongyun", "element": "Cryo", "rarity": 4, "icon_name": "UI_AvatarIcon_Chongyun"},
    10000067: {"name": "Collei", "element": "Dendro", "rarity": 4, "icon_name": "UI_AvatarIcon_Collei"},
    10000115: {"name": "Dahlia", "element": "Hydro", "rarity": 4, "icon_name": "UI_AvatarIcon_Dahlia"},
    10000039: {"name": "Diona", "element": "Cryo", "rarity": 4, "icon_name": "UI_AvatarIcon_Diona"},
    10000068: {"name": "Dori", "element": "Electro", "rarity": 4, "icon_name": "UI_AvatarIcon_Dori"},
    10000076: {"name": "Faruzan", "element": "Anemo", "rarity": 4, "icon_name": "UI_AvatarIcon_Faruzan"},
    10000031: {"name": "Fischl", "element": "Electro", "rarity": 4, "icon_name": "UI_AvatarIcon_Fischl"},
    10000085: {"name": "Freminet", "element": "Cryo", "rarity": 4, "icon_name": "UI_AvatarIcon_Freminet"},
    10000092: {"name": "Gaming", "element": "Pyro", "rarity": 4, "icon_name": "UI_AvatarIcon_Gaming"},
    10000055: {"name": "Gorou", "element": "Geo", "rarity": 4, "icon_name": "UI_AvatarIcon_Gorou"},
    11000046: {"name": "Hỏa Thần (Test)", "element": "Cryo", "rarity": 4, "icon_name": "UI_AvatarIcon_Qin"},
    10000110: {"name": "Iansan", "element": "Electro", "rarity": 4, "icon_name": "UI_AvatarIcon_Iansan"},
    10000113: {"name": "Ifa", "element": "Anemo", "rarity": 4, "icon_name": "UI_AvatarIcon_Ifa"},
    10000124: {"name": "Jahoda", "element": "Anemo", "rarity": 4, "icon_name": "UI_AvatarIcon_Jahoda"},
    10000100: {"name": "Kachina", "element": "Geo", "rarity": 4, "icon_name": "UI_AvatarIcon_Kachina"},
    10000015: {"name": "Kaeya", "element": "Cryo", "rarity": 4, "icon_name": "UI_AvatarIcon_Kaeya"},
    10000081: {"name": "Kaveh", "element": "Dendro", "rarity": 4, "icon_name": "UI_AvatarIcon_Kaveh"},
    10000061: {"name": "Kirara", "element": "Dendro", "rarity": 4, "icon_name": "UI_AvatarIcon_Momoka"},
    10000056: {"name": "Kujou Sara", "element": "Electro", "rarity": 4, "icon_name": "UI_AvatarIcon_Sara"},
    10000065: {"name": "Kuki Shinobu", "element": "Electro", "rarity": 4, "icon_name": "UI_AvatarIcon_Shinobu"},
    10000108: {"name": "Lan Yan", "element": "Anemo", "rarity": 4, "icon_name": "UI_AvatarIcon_Lanyan"},
    10000074: {"name": "Layla", "element": "Cryo", "rarity": 4, "icon_name": "UI_AvatarIcon_Layla"},
    10000006: {"name": "Lisa", "element": "Electro", "rarity": 4, "icon_name": "UI_AvatarIcon_Lisa"},
    10000083: {"name": "Lynette", "element": "Anemo", "rarity": 4, "icon_name": "UI_AvatarIcon_Linette"},
    10000080: {"name": "Mika", "element": "Cryo", "rarity": 4, "icon_name": "UI_AvatarIcon_Mika"},
    10000117: {"name": "Nhân vật #10000117", "element": "None", "rarity": 4, "icon_name": ""},
    10000118: {"name": "Nhân vật #10000118", "element": "None", "rarity": 4, "icon_name": ""},
    10000998: {"name": "Nhân vật #10000998", "element": "None", "rarity": 4, "icon_name": ""},
    10000999: {"name": "Nhân vật #10000999", "element": "None", "rarity": 4, "icon_name": ""},
    11000998: {"name": "Nhân vật #11000998", "element": "None", "rarity": 4, "icon_name": ""},
    11000999: {"name": "Nhân vật #11000999", "element": "None", "rarity": 4, "icon_name": ""},
    10000027: {"name": "Ningguang", "element": "Geo", "rarity": 4, "icon_name": "UI_AvatarIcon_Ningguang"},
    10000034: {"name": "Noelle", "element": "Geo", "rarity": 4, "icon_name": "UI_AvatarIcon_Noel"},
    10000105: {"name": "Ororon", "element": "Electro", "rarity": 4, "icon_name": "UI_AvatarIcon_Olorun"},
    10000020: {"name": "Razor", "element": "Electro", "rarity": 4, "icon_name": "UI_AvatarIcon_Razor"},
    10000045: {"name": "Rosaria", "element": "Cryo", "rarity": 4, "icon_name": "UI_AvatarIcon_Rosaria"},
    10000053: {"name": "Sayu", "element": "Anemo", "rarity": 4, "icon_name": "UI_AvatarIcon_Sayu"},
    10000097: {"name": "Sethos", "element": "Electro", "rarity": 4, "icon_name": "UI_AvatarIcon_Sethos"},
    10000059: {"name": "Shikanoin Heizou", "element": "Anemo", "rarity": 4, "icon_name": "UI_AvatarIcon_Heizo"},
    10000043: {"name": "Sucrose", "element": "Anemo", "rarity": 4, "icon_name": "UI_AvatarIcon_Sucrose"},
    10000050: {"name": "Thoma", "element": "Pyro", "rarity": 4, "icon_name": "UI_AvatarIcon_Tohma"},
    10000023: {"name": "Xiangling", "element": "Pyro", "rarity": 4, "icon_name": "UI_AvatarIcon_Xiangling"},
    10000025: {"name": "Xingqiu", "element": "Hydro", "rarity": 4, "icon_name": "UI_AvatarIcon_Xingqiu"},
    10000044: {"name": "Xinyan", "element": "Pyro", "rarity": 4, "icon_name": "UI_AvatarIcon_Xinyan"},
    10000048: {"name": "Yanfei", "element": "Pyro", "rarity": 4, "icon_name": "UI_AvatarIcon_Feiyan"},
    10000077: {"name": "Yaoyao", "element": "Dendro", "rarity": 4, "icon_name": "UI_AvatarIcon_Yaoyao"},
    10000064: {"name": "Yun Jin", "element": "Geo", "rarity": 4, "icon_name": "UI_AvatarIcon_Yunjin"},
}

# Màu sắc đại diện cho các nguyên tố Genshin
ELEMENT_COLORS = {
    "Pyro": 0xEC4923,
    "Hydro": 0x00BFFF,
    "Anemo": 0x35DBA4,
    "Electro": 0xA256E1,
    "Dendro": 0x60DB35,
    "Cryo": 0x7BE4F9,
    "Geo": 0xE3B342,
    "None": 0xA0A0A0,
}

# Ánh xạ ID FightProp sang tên chuẩn
FIGHT_PROP_MAP = {
    1: ("FIGHT_PROP_BASE_HP", False),
    2: ("FIGHT_PROP_HP", False),
    3: ("FIGHT_PROP_HP_PERCENT", True),
    4: ("FIGHT_PROP_BASE_ATTACK", False),
    5: ("FIGHT_PROP_ATTACK", False),
    6: ("FIGHT_PROP_ATTACK_PERCENT", True),
    7: ("FIGHT_PROP_BASE_DEFENSE", False),
    8: ("FIGHT_PROP_DEFENSE", False),
    9: ("FIGHT_PROP_DEFENSE_PERCENT", True),
    20: ("FIGHT_PROP_CRITICAL", True),
    22: ("FIGHT_PROP_CRITICAL_HURT", True),
    23: ("FIGHT_PROP_CHARGE_EFFICIENCY", True),
    26: ("FIGHT_PROP_HEAL_ADD", True),
    28: ("FIGHT_PROP_ELEMENT_MASTERY", False),
    30: ("FIGHT_PROP_PHYSICAL_ADD_HURT", True),
    40: ("FIGHT_PROP_FIRE_ADD_HURT", True),
    41: ("FIGHT_PROP_ELEC_ADD_HURT", True),
    42: ("FIGHT_PROP_WATER_ADD_HURT", True),
    43: ("FIGHT_PROP_GRASS_ADD_HURT", True),
    44: ("FIGHT_PROP_WIND_ADD_HURT", True),
    45: ("FIGHT_PROP_ROCK_ADD_HURT", True),
    46: ("FIGHT_PROP_ICE_ADD_HURT", True),
    2000: ("MAX_HP", False),
    2001: ("CUR_ATTACK", False),
    2002: ("CUR_DEFENSE", False),
}
