"""Các hằng số và danh mục nhân vật Honkai: Star Rail."""

from typing import Dict, Any

# Bảng mã nhân vật Honkai: Star Rail (ID -> (Tên tiếng Việt, Vận Mệnh, Thuộc Tính, Rarity))
HSR_CHARACTERS: Dict[int, Dict[str, Any]] = {
    1308: {"name": "Acheron", "path": "Hư Vô", "element": "Lôi", "rarity": 5},
    1402: {"name": "Aglaea", "path": "Ký Ức", "element": "Lôi", "rarity": 5},
    1405: {"name": "Anaxa", "path": "Tri Thức", "element": "Phong", "rarity": 5},
    1015: {"name": "Archer", "path": "Săn Bắn", "element": "Lượng Tử", "rarity": 5},
    1302: {"name": "Argenti", "path": "Tri Thức", "element": "Vật Lý", "rarity": 5},
    1504: {"name": "Ashveil", "path": "Săn Bắn", "element": "Lôi", "rarity": 5},
    1304: {"name": "Aventurine", "path": "Bảo Hộ", "element": "Số Ảo", "rarity": 5},
    1513: {"name": "Aventurine - Waveflair", "path": "Hoan Lạc", "element": "Lượng Tử", "rarity": 5},
    1211: {"name": "Bailu", "path": "Trù Phú", "element": "Lôi", "rarity": 5},
    1307: {"name": "Black Swan", "path": "Hư Vô", "element": "Phong", "rarity": 5},
    1205: {"name": "Blade", "path": "Hủy Diệt", "element": "Phong", "rarity": 5},
    1315: {"name": "Boothill", "path": "Săn Bắn", "element": "Vật Lý", "rarity": 5},
    1101: {"name": "Bronya", "path": "Hòa Hợp", "element": "Phong", "rarity": 5},
    1407: {"name": "Castorice", "path": "Ký Ức", "element": "Lượng Tử", "rarity": 5},
    1412: {"name": "Cerydra", "path": "Hòa Hợp", "element": "Phong", "rarity": 5},
    1406: {"name": "Cipher", "path": "Hư Vô", "element": "Lượng Tử", "rarity": 5},
    1107: {"name": "Clara", "path": "Hủy Diệt", "element": "Vật Lý", "rarity": 5},
    1415: {"name": "Cyrene", "path": "Ký Ức", "element": "Băng", "rarity": 5},
    1321: {"name": "Dahlia", "path": "Hư Vô", "element": "Hỏa", "rarity": 5},
    1414: {"name": "Dan Heng - Permansor Terrae", "path": "Bảo Hộ", "element": "Vật Lý", "rarity": 5},
    1213: {"name": "Dan Heng - Ẩm Nguyệt", "path": "Hủy Diệt", "element": "Số Ảo", "rarity": 5},
    1305: {"name": "Dr. Ratio", "path": "Săn Bắn", "element": "Số Ảo", "rarity": 5},
    1505: {"name": "Evanescia", "path": "Hoan Lạc", "element": "Vật Lý", "rarity": 5},
    1413: {"name": "Evernight", "path": "Ký Ức", "element": "Băng", "rarity": 5},
    1220: {"name": "Feixiao", "path": "Săn Bắn", "element": "Phong", "rarity": 5},
    1310: {"name": "Firefly", "path": "Hủy Diệt", "element": "Hỏa", "rarity": 5},
    1208: {"name": "Fu Xuan", "path": "Bảo Hộ", "element": "Lượng Tử", "rarity": 5},
    1225: {"name": "Fugue", "path": "Hư Vô", "element": "Hỏa", "rarity": 5},
    1104: {"name": "Gepard", "path": "Bảo Hộ", "element": "Băng", "rarity": 5},
    1509: {"name": "Gilgamesh", "path": "Hủy Diệt", "element": "Lôi", "rarity": 5},
    1003: {"name": "Himeko", "path": "Tri Thức", "element": "Hỏa", "rarity": 5},
    1510: {"name": "Himeko - Nova", "path": "Tri Thức", "element": "Hỏa", "rarity": 5},
    1217: {"name": "Huohuo", "path": "Trù Phú", "element": "Phong", "rarity": 5},
    1409: {"name": "Hyacine", "path": "Ký Ức", "element": "Phong", "rarity": 5},
    1410: {"name": "Hysilens", "path": "Hư Vô", "element": "Vật Lý", "rarity": 5},
    1314: {"name": "Jade", "path": "Tri Thức", "element": "Lượng Tử", "rarity": 5},
    1218: {"name": "Jiaoqiu", "path": "Hư Vô", "element": "Hỏa", "rarity": 5},
    1204: {"name": "Jing Yuan", "path": "Tri Thức", "element": "Lôi", "rarity": 5},
    1212: {"name": "Jingliu", "path": "Hủy Diệt", "element": "Băng", "rarity": 5},
    1005: {"name": "Kafka", "path": "Hư Vô", "element": "Lôi", "rarity": 5},
    1222: {"name": "Lingsha", "path": "Trù Phú", "element": "Hỏa", "rarity": 5},
    1203: {"name": "Luocha", "path": "Trù Phú", "element": "Số Ảo", "rarity": 5},
    1507: {"name": "Mortenax Blade", "path": "Hư Vô", "element": "Hỏa", "rarity": 5},
    1404: {"name": "Mydei", "path": "Hủy Diệt", "element": "Số Ảo", "rarity": 5},
    1503: {"name": "Pearl", "path": "Hoan Lạc", "element": "Băng", "rarity": 5},
    1408: {"name": "Phainon", "path": "Hủy Diệt", "element": "Vật Lý", "rarity": 5},
    1317: {"name": "Rappa", "path": "Tri Thức", "element": "Số Ảo", "rarity": 5},
    1508: {"name": "Rin Tohsaka", "path": "Tri Thức", "element": "Lượng Tử", "rarity": 5},
    1309: {"name": "Robin", "path": "Hòa Hợp", "element": "Vật Lý", "rarity": 5},
    1512: {"name": "Robin - Summeretto", "path": "Ký Ức", "element": "Phong", "rarity": 5},
    1303: {"name": "Ruan Mei", "path": "Hòa Hợp", "element": "Băng", "rarity": 5},
    1014: {"name": "Saber", "path": "Hủy Diệt", "element": "Phong", "rarity": 5},
    1102: {"name": "Seele", "path": "Săn Bắn", "element": "Lượng Tử", "rarity": 5},
    1306: {"name": "Sparkle", "path": "Hòa Hợp", "element": "Lượng Tử", "rarity": 5},
    1501: {"name": "Sparxie", "path": "Hoan Lạc", "element": "Hỏa", "rarity": 5},
    1313: {"name": "Sunday", "path": "Hòa Hợp", "element": "Số Ảo", "rarity": 5},
    1006: {"name": "Sói Bạc", "path": "Hư Vô", "element": "Lượng Tử", "rarity": 5},
    1506: {"name": "Sói Bạc LV.999", "path": "Hoan Lạc", "element": "Số Ảo", "rarity": 5},
    1112: {"name": "Topaz & Numby", "path": "Săn Bắn", "element": "Hỏa", "rarity": 5},
    1403: {"name": "Tribbie", "path": "Hòa Hợp", "element": "Lượng Tử", "rarity": 5},
    1004: {"name": "Welt", "path": "Hư Vô", "element": "Số Ảo", "rarity": 5},
    1209: {"name": "Yanqing", "path": "Săn Bắn", "element": "Băng", "rarity": 5},
    1502: {"name": "Yao Guang", "path": "Hoan Lạc", "element": "Vật Lý", "rarity": 5},
    1221: {"name": "Yunli", "path": "Hủy Diệt", "element": "Vật Lý", "rarity": 5},
    8001: {"name": "Nhà Khai Phá", "path": "Hủy Diệt", "element": "Vật Lý", "rarity": 5},
    8002: {"name": "Nhà Khai Phá", "path": "Hủy Diệt", "element": "Vật Lý", "rarity": 5},
    8003: {"name": "Nhà Khai Phá", "path": "Bảo Hộ", "element": "Hỏa", "rarity": 5},
    8004: {"name": "Nhà Khai Phá", "path": "Bảo Hộ", "element": "Hỏa", "rarity": 5},
    8005: {"name": "Nhà Khai Phá", "path": "Hòa Hợp", "element": "Số Ảo", "rarity": 5},
    8006: {"name": "Nhà Khai Phá", "path": "Hòa Hợp", "element": "Số Ảo", "rarity": 5},
    8007: {"name": "Nhà Khai Phá", "path": "Ký Ức", "element": "Băng", "rarity": 5},
    8008: {"name": "Nhà Khai Phá", "path": "Ký Ức", "element": "Băng", "rarity": 5},
    8009: {"name": "Nhà Khai Phá", "path": "Hoan Lạc", "element": "Lôi", "rarity": 5},
    8010: {"name": "Nhà Khai Phá", "path": "Hoan Lạc", "element": "Lôi", "rarity": 5},
    1401: {"name": "Đại Herta", "path": "Tri Thức", "element": "Băng", "rarity": 5},
    1008: {"name": "Arlan", "path": "Hủy Diệt", "element": "Lôi", "rarity": 4},
    1009: {"name": "Asta", "path": "Hòa Hợp", "element": "Hỏa", "rarity": 4},
    1002: {"name": "Dan Heng", "path": "Săn Bắn", "element": "Phong", "rarity": 4},
    1301: {"name": "Gallagher", "path": "Trù Phú", "element": "Hỏa", "rarity": 4},
    1210: {"name": "Guinaifen", "path": "Hư Vô", "element": "Hỏa", "rarity": 4},
    1215: {"name": "Hanya", "path": "Hòa Hợp", "element": "Vật Lý", "rarity": 4},
    1013: {"name": "Herta", "path": "Tri Thức", "element": "Băng", "rarity": 4},
    1109: {"name": "Hook", "path": "Hủy Diệt", "element": "Hỏa", "rarity": 4},
    1111: {"name": "Luka", "path": "Hư Vô", "element": "Vật Lý", "rarity": 4},
    1110: {"name": "Lynx", "path": "Trù Phú", "element": "Lượng Tử", "rarity": 4},
    1001: {"name": "March 7th", "path": "Bảo Hộ", "element": "Băng", "rarity": 4},
    1224: {"name": "March 7th", "path": "Săn Bắn", "element": "Số Ảo", "rarity": 4},
    1312: {"name": "Misha", "path": "Hủy Diệt", "element": "Băng", "rarity": 4},
    1223: {"name": "Moze", "path": "Săn Bắn", "element": "Lôi", "rarity": 4},
    1105: {"name": "Natasha", "path": "Trù Phú", "element": "Vật Lý", "rarity": 4},
    1106: {"name": "Pela", "path": "Hư Vô", "element": "Băng", "rarity": 4},
    1201: {"name": "Qingque", "path": "Tri Thức", "element": "Lượng Tử", "rarity": 4},
    1108: {"name": "Sampo", "path": "Hư Vô", "element": "Phong", "rarity": 4},
    1103: {"name": "Serval", "path": "Tri Thức", "element": "Lôi", "rarity": 4},
    1206: {"name": "Sushang", "path": "Săn Bắn", "element": "Vật Lý", "rarity": 4},
    1202: {"name": "Tingyun", "path": "Hòa Hợp", "element": "Lôi", "rarity": 4},
    1214: {"name": "Xueyi", "path": "Hủy Diệt", "element": "Lượng Tử", "rarity": 4},
    1207: {"name": "Yukong", "path": "Hòa Hợp", "element": "Số Ảo", "rarity": 4},
}

# Màu sắc đại diện cho các nguyên tố HSR
HSR_ELEMENT_COLORS = {
    "Vật Lý": 0xA0A0A0,
    "Hỏa": 0xEC4923,
    "Băng": 0x7BE4F9,
    "Lôi": 0xA256E1,
    "Phong": 0x35DBA4,
    "Lượng Tử": 0x5056E0,
    "Số Ảo": 0xE3B342,
    "None": 0xA0A0A0,
}
